/// Flutter icons DomoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DomoIcons
///      fonts:
///       - asset: fonts/DomoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DomoIcons {
  DomoIcons._();

  static const _kFontFam = 'DomoIcons';
  static const String? _kFontPkg = null;

  static const IconData burger = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkboxcircule = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheklist = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key7boardleft = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardchecklist = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardlists = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardorderedlist = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardredo = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardright = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardtextformat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardundo = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardunorderedlist = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textcheckboxactive = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData textcheckboxinactive = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accept = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h3 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h1 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
